language: node_js

node_js:
    - "4.0"

sudo: false

cache:
  directories:
    - ~/.npm
    - ~/node_modules

before_install:
  - npm install phantomjs -g
  - npm install -g benderjs-cli

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bender init
